CREATE TABLE IF NOT EXISTS Person(
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	full_name varchar(200) NOT NULL,
	year_of_birth int CHECK (year_of_birth > 1901)
);

CREATE TABLE IF NOT EXISTS Book(
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	title varchar(200) NOT NULL,
	author varchar(200) NOT NULL,
	year_of_publishing int CHECK (year_of_publishing <= 2024 AND year_of_publishing > 0),
	person_owner_id int REFERENCES Person (id)
);